// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Amit Tomar's public profile: headline, summary, location, education and contact links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Amit Tomar",
      headline: "Data Analyst & Business Intelligence Specialist",
      summary: "Detail-oriented Data Analyst with hands-on experience in SQL, Excel, Python and Power BI. Passionate about transforming raw data into actionable insights that drive business decisions.",
      location: "Gwalior, MP, India",
      education: {
        degree: "B.Tech in Mathematics & Computing",
        institution: "Madhav Institute of Technology & Science, Gwalior",
        years: "2022 - 2026"
      },
      contact: {
        email: "amyttomar@gmail.com",
        phone: "+91 7389671194",
        linkedin: "https://www.linkedin.com/in/amit-tomar-47583a2a7",
        github: "https://github.com/Amittomar2003"
      },
      highlights: {
        projectsCompleted: "15+",
        dataSourcesAnalyzed: "50+",
        efficiencyImprovement: "25%",
        cancellationReduction: "20%"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_skills_default = defineTool2({
  name: "list_skills",
  title: "List skills",
  description: "List Amit Tomar's technical skills and tools with proficiency levels, grouped by category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const skills = {
      categories: [
        {
          title: "Data Analysis",
          skills: [
            { name: "SQL", level: 90 },
            { name: "Excel", level: 85 },
            { name: "Power BI", level: 88 },
            { name: "Python", level: 75 }
          ]
        },
        {
          title: "Visualization",
          skills: [
            { name: "Power BI Dashboards", level: 90 },
            { name: "Data Storytelling", level: 85 },
            { name: "KPI Tracking", level: 88 },
            { name: "Interactive Reports", level: 80 }
          ]
        },
        {
          title: "Technical",
          skills: [
            { name: "Database Design", level: 80 },
            { name: "Data Cleaning", level: 92 },
            { name: "ETL Processes", level: 75 },
            { name: "Statistical Analysis", level: 70 }
          ]
        }
      ],
      tools: [
        "SQL Server",
        "Power BI",
        "Excel",
        "Python",
        "Analytics",
        "Visualization"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(skills, null, 2) }],
      structuredContent: skills
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List projects",
  description: "List Amit Tomar's featured data analytics projects with impact, technologies, key results and links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const projects = [
      {
        title: "OLA Ride Cancellation Analysis",
        description: "Identified key reasons and trends for ride cancellations using SQL data processing and Power BI visualization.",
        impact: "20% reduction in cancellation rate",
        technologies: ["SQL", "Power BI", "Data Cleaning", "Trend Analysis"],
        results: [
          "Processed multi-source data using advanced SQL queries",
          "Created interactive dashboards for stakeholder insights",
          "Identified peak cancellation patterns and root causes"
        ],
        link: "https://app.powerbi.com/groups/me/reports/35565868-1ebd-42a9-b36d-91bb46f35b7e?experience=power-bi"
      },
      {
        title: "Hospital Performance Tracker",
        description: "Comprehensive Power BI dashboard tracking key hospital performance metrics and business trends.",
        impact: "25% improvement in decision-making efficiency",
        technologies: ["Power BI", "SQL", "KPI Tracking", "Interactive Dashboards"],
        results: [
          "Extracted and transformed data from multiple sources",
          "Built real-time KPI monitoring system",
          "Enabled drill-down analytics for detailed insights"
        ],
        link: "https://app.powerbi.com/links/Df2tQioFdx?ctid=4fd60770-0a1d-4047-b029-26a2cc4b34e2&pbi_source=linkShare"
      },
      {
        title: "Customer Shopping Behavior Analysis",
        description: "End-to-end analytics workflow turning raw customer data into strategic business intelligence \u2014 from cleaning and modeling in Python to SQL analysis and an interactive Power BI dashboard.",
        impact: "Full end-to-end analytics pipeline",
        technologies: ["Python", "SQL", "Power BI", "EDA", "Data Modeling"],
        results: [
          "Cleaned, transformed and explored the raw dataset in Python",
          "Ran SQL queries on customer segments, loyalty and purchase drivers",
          "Built an interactive Power BI dashboard highlighting key trends"
        ],
        link: "https://github.com/Amittomar2003/Customer-trend-analysis"
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
      structuredContent: { projects }
    };
  }
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_experience_default = defineTool4({
  name: "get_experience",
  title: "Get experience and education",
  description: "Get Amit Tomar's professional experience and education history, including internships and certifications.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = {
      experience: [
        {
          role: "Data Analyst Intern",
          organization: "Elevate Labs (Skill India - Ministry of MSME)",
          period: "June 2025 - July 2025",
          location: "Remote",
          badge: "Best Performer",
          highlights: [
            "Successfully completed comprehensive Data Analyst Internship program",
            "Demonstrated strong analytical thinking and problem-solving skills",
            "Recognized as Best Performer among all participants",
            "Applied data analysis techniques to real-world business scenarios"
          ]
        }
      ],
      education: [
        {
          degree: "B.Tech in Mathematics & Computing",
          institution: "Madhav Institute of Technology & Science, Gwalior",
          period: "2022 - 2026"
        }
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "amit-tomar-portfolio-mcp",
  title: "Amit Tomar Portfolio MCP",
  version: "0.1.0",
  instructions: "Public tools exposing Amit Tomar's data-analyst portfolio. Use `get_profile` for bio and contact links, `list_skills` for tools and proficiency, `list_projects` for featured analytics projects, and `get_experience` for work history and education.",
  tools: [get_profile_default, list_skills_default, list_projects_default, get_experience_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
